name: Android Lint Check
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
      - develop
      - release/**
      - bugfix/**
      - hotfix/**

jobs:
  build:
    # Job name is Greeting
    name: Android Lint
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1

      - run: ./gradlew lint



