name: Lint Check
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Detekt
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
          uses: actions/checkout@v2

      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.9.1
        with:
          args: '--fail-fast'


