name: Lint Check
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  detekt:
    # Job name is Greeting
    name: Detekt
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1

      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.9.1
#        with:
#          args: --fail-fast

  build:
    name: Test

      - name: Hello world
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: 'Mona the Octocat'
          id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'


