name: Lint Check
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  detekt:
    # Job name is Greeting
    name: Detekt
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1

      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.9.1
        with:
          args: --fail-fast


